host: '192.168.1.103'
port: 8848
namespace: 'c1872978-d51c-4188-a497-4e0cd20b97d5'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'

mysql:
  host: "127.0.0.1"
  port: 3307
  user: root
  password: root
  db: mxshop_user_srv

consul:
  host: "127.0.0.1"
  port: 8500

